### PR TITLE
Upkeep and GHC 9.4 compatibility.

### LINKED ISSUE #13: fails to build with ghc-9.4/Cabal-3.8 for Stackage Nightly
```
Building library for cabal-file-th-0.2.7..                        
[1 of 1] Compiling Distribution.PackageDescription.TH                                                                               

/var/stackage/work/unpack-dir/unpacked/cabal-file-th-0.2.7-240f7246da4bace570a5a9a827da94bd4b27a2be7cd2aa37094dd335f2822ed6/Distribu
tion/PackageDescription/TH.hs:45:48: error:
    Module                                                        
    ‘Distribution.PackageDescription.Parsec’                                                                                        
    does not export                                               
    ‘readGenericPackageDescription’                               
   |                                                              
45 | import Distribution.PackageDescription.Parsec (readGenericPackageDescription)                                                  
   |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
```

### PR DESCRIPTION
**Pull request by kamek-pf**
Minor fixes to allow GHC 9.4.

Also fixes tests, broken since GHC 8.10.
I tested the latest minor releases all the way back to GHC 8.8.4, the tests are passing and there are no warnings.

Fixes #13.

Cheers :)

### CODE REVIEW

**Comment by nkpart** [comment]
Thanks very much!

**Comment by kamek-pf** [comment]
Thanks for the quick review !
When you have a minute to spare, it'd be great if you could publish the new version to Hackage.

**Comment by juhp** [comment]
+1 for a release
