### ISSUE TITLE
fails to build with ghc-9.4/Cabal-3.8 for Stackage Nightly

### ISSUE THREAD

**Issue by juhp** [nkpart/cabal-file-th#13]
```
Building library for cabal-file-th-0.2.7..                        
[1 of 1] Compiling Distribution.PackageDescription.TH                                                                               

/var/stackage/work/unpack-dir/unpacked/cabal-file-th-0.2.7-240f7246da4bace570a5a9a827da94bd4b27a2be7cd2aa37094dd335f2822ed6/Distribu
tion/PackageDescription/TH.hs:45:48: error:
    Module                                                        
    ‘Distribution.PackageDescription.Parsec’                                                                                        
    does not export                                               
    ‘readGenericPackageDescription’                               
   |                                                              
45 | import Distribution.PackageDescription.Parsec (readGenericPackageDescription)                                                  
   |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
```
